apiVersion: "config.istio.io/v1alpha2"
kind: listchecker
metadata:
  name: preferencewhitelist
  namespace: user1-tutorial
spec:
  overrides: ["v1", "v3"]
  blacklist: false
---
apiVersion: "config.istio.io/v1alpha2"
kind: listentry
metadata:
  name: preferencesource
  namespace: user1-tutorial
spec:
  value: destination.labels["version"]
---
apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
  name: checktorecommendation
  namespace: user1-tutorial
spec:
  match: destination.labels["app"] == "recommendation"
  actions:
  - handler: preferencewhitelist.listchecker
    instances:
    - preferencesource.listentry
