apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: "preference-mutualtls"
  namespace: user1-tutorial
spec:
  targets:
  - name: preference
  peers:
  - mtls: 
      mode: PERMISSIVE