apiVersion: "config.istio.io/v1alpha2"
kind: metric
metadata:
  name: recommendationrequestcount
  namespace: user1-smcp
spec:
  value: "1"
  dimensions:
    source: source.service | "unknown"
    destination: destination.service | "unknown"
    version: destination.labels["version"] | "unknown"
    user_agent: request.headers["user-agent"] | "unknown"
  monitored_resource_type: '"UNSPECIFIED"'
---
apiVersion: "config.istio.io/v1alpha2"
kind: prometheus
metadata:
  name: recommendationrequestcounthandler
  namespace: user1-smcp
spec:
  metrics:
  - name: recommendation_request_count
    instance_name: recommendationrequestcount.metric.user1-smcp
    kind: COUNTER
    label_names:
    - source
    - destination
    - user_agent
    - version
---
apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
  name: recommendationrequestcountprom
  namespace: user1-smcp
spec:
  match: destination.service == "recommendation.user1-tutorial.svc.cluster.local"
  actions:
  - handler: recommendationrequestcounthandler.prometheus
    instances:
    - recommendationrequestcount.metric
